{% set name = "pyfes" %}
{% set version = "2.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}
  
source:
  url: https://bitbucket.org/cnes_aviso/fes/downloads/fes-2.9.2-Source.tar.xz
  sha256: 16c90f163f797c2004f3856995d796a5394fd276e6f4103560e5a2da9ca8f485

requirements:
  build:
    - {{ compiler('cxx') }}  # [linux or osx]
    - vs2017_win-64          # [win]
    - cmake
  host:
    - python {{ python }}
    - libnetcdf
    - setuptools
  run:
    - {{ pin_compatible('numpy') }}
    - python
    - libnetcdf

test:
  imports:
    - pyfes

about:
  home: https://bitbucket.org/cnes_aviso/fes
  license: GNU Lesser General Public License v3
  license_family: LGPL
  license_file: COPYING
  summary: 'FES2014 prediction software'
  description: |
    This package is the fully revised version of the FES2014 distribution.
    This distribution includes the FES2014 tidal prediction software and
    the FES2014 tides databases

extra:
  recipe-maintainers:
    - fbriol
