package:
  name: fes
  version: 2.9.1

source:
  url: https://bitbucket.org/cnes_aviso/fes/downloads/fes-2.9.1-Source.tar.xz
  sha256: f5a8188943b3b8a1fc70f4655d5d8fb8bb6fdd7e51b6c7ce55a47d28e0162b56

requirements:
  build:
    - cmake
    - libnetcdf
    - python {{ python }}
    - setuptools
  run:
    - python {{ python }}
    - libnetcdf
    - numpy

test:
  imports:
    - pyfes
