import collections.abc
import numpy
import typing

from ..type_hints import (
    MatrixComplex128,
    MatrixFloat64,
    VectorComplex128,
    VectorFloat64,
)

from . import (
    AstronomicAngle,
    TidalType,
    Formulae,
    FesRuntimeSettings,
    ConstituentMap,
)

class LongPeriodEquilibrium:
    def __init__(self) -> None: ...
    def disable_dynamic_wave(self, wave_table: WaveTable) -> None: ...
    def lpe_minus_n_waves(
        self, angles: AstronomicAngle, lat: typing.SupportsFloat
    ) -> float: ...

class Wave:
    admittance: bool
    dynamic: bool
    tide: complex
    def doodson_numbers(self, *args, **kwargs): ...
    def name(self) -> str: ...
    def nodal_a(self, a: AstronomicAngle) -> None: ...
    def nodal_g(self, a: AstronomicAngle) -> None: ...
    def period(self) -> float: ...
    def v(self) -> float: ...
    def vu(self) -> float: ...
    def xdo_alphabetical(self) -> str: ...
    def xdo_numerical(self) -> str: ...
    @property
    def f(self) -> float: ...
    @property
    def freq(self) -> float: ...
    @property
    def type(self) -> TidalType: ...
    @property
    def u(self) -> float: ...

class WaveTable:
    def __init__(self, waves: collections.abc.Sequence[str] | None = ...) -> None: ...
    def admittance(self) -> None: ...
    def compute_nodal_corrections(self, angles: AstronomicAngle) -> None: ...
    def compute_nodal_modulations(
        self, dates: numpy.ndarray, formulae: Formulae = ...
    ) -> tuple[
        MatrixFloat64,
        MatrixFloat64,
    ]: ...
    @staticmethod
    def harmonic_analysis(
        h: VectorFloat64,
        f: MatrixFloat64,
        vu: MatrixFloat64,
    ) -> VectorComplex128: ...
    def keys(self) -> list[str]: ...
    @staticmethod
    def select_waves_for_analysis(
        duration: typing.SupportsFloat, f: typing.SupportsFloat = ...
    ) -> list[str]: ...
    def tide_from_mapping(
        self,
        date: object,
        mapping: MatrixComplex128,
        formulae: Formulae = ...,
        num_threads: typing.SupportsInt = ...,
    ) -> MatrixFloat64: ...
    def tide_from_tide_series(
        self,
        dates: numpy.ndarray,
        wave: VectorComplex128,
        formulae: Formulae = ...,
    ) -> VectorFloat64: ...
    def values(self) -> list[Wave]: ...
    def __contains__(self, index: str) -> bool: ...
    def __getitem__(self, index: str) -> Wave: ...
    def __iter__(self) -> collections.abc.Iterator[Wave]: ...
    def __len__(self) -> int: ...

def constituents() -> ConstituentMap: ...
def evaluate_equilibrium_long_period(
    dates: numpy.ndarray,
    latitudes: VectorFloat64,
    settings: FesRuntimeSettings | None = ...,
) -> VectorFloat64: ...
