from ..type_hints import VectorFloat64, MatrixInt32

class Index:
    def __init__(
        self, lon: VectorFloat64, lat: VectorFloat64, triangles: MatrixInt32
    ) -> None: ...
    def lat(self) -> VectorFloat64: ...
    def lon(self) -> VectorFloat64: ...
    def memory_usage(self) -> int: ...
    def triangles(self) -> MatrixInt32: ...
