import collections.abc

from ..type_hints import (
    VectorInt8,
)

from . import TidalType, ConstituentMap

class Wave:
    def __init__(self, *args, **kwargs) -> None: ...
    def name(self) -> str: ...
    def xdo_alphabetical(self) -> str: ...
    def xdo_numerical(self) -> str: ...
    @property
    def doodson_number(self) -> VectorInt8: ...
    @property
    def freq(self) -> float: ...
    @property
    def is_inferred(self) -> bool: ...
    @property
    def tidal_argument(self) -> float: ...
    @property
    def tide(self) -> complex: ...
    @property
    def type(self) -> TidalType: ...

class WaveTable:
    def __init__(
        self, constituents: collections.abc.Sequence[str] | None = ...
    ) -> None: ...
    def keys(self) -> list[str]: ...
    def values(self) -> list[Wave]: ...
    def __getitem__(self, constituent: str) -> Wave: ...
    def __len__(self) -> int: ...

def constituents() -> ConstituentMap: ...
