import collections.abc
from typing import overload

from ..type_hints import VectorInt8

from . import FrequencyUnit, WaveInterface, WaveTableInterface, WaveType

class Wave(WaveInterface):
    def doodson_numbers(self) -> VectorInt8: ...
    def frequency(self, unit: FrequencyUnit = ...) -> float: ...
    def xdo_alphabetical(self) -> str: ...
    def xdo_numerical(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def period(self) -> float: ...
    @property
    def type(self) -> WaveType: ...

class WaveTable(WaveTableInterface):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, names: collections.abc.Sequence[str]) -> None: ...
