{% set name = "pyfes" %}
{% set version = "2.9.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}
  
source:
  git_url: https://github.com/CNES/aviso-fes
  git_rev: HEAD

requirements:
  build:
    - {{ compiler('cxx') }}  # [linux or osx]
    - vs2017_win-64          # [win]
    - make                   # [linux or osx]
    - cmake
  host:
    - python {{ python }}
    - libnetcdf
    - setuptools
  run:
    - {{ pin_compatible('numpy') }}
    - python
    - libnetcdf

test:
  imports:
    - pyfes

about:
  home: https://bitbucket.org/cnes_aviso/fes
  license: GNU Lesser General Public License v3
  license_family: LGPL
  license_file: COPYING
  summary: 'FES2014 prediction software'
  description: |
    This package is the fully revised version of the FES2014 distribution.
    This distribution includes the FES2014 tidal prediction software and
    the FES2014 tides databases

extra:
  recipe-maintainers:
    - fbriol
