{% set name = "pyfes" %}
{% set version = "2.9.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/CNES/aviso-fes
  git_rev: HEAD

build:
  script: {{ PYTHON }} -m pip install . -vv
  build: 0

requirements:
  build:
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - setuptools                          # [build_platform != target_platform]
    - {{ compiler('cxx') }}               # [linux or osx]
    - vs2017_win-64                       # [win]
    - cmake
    - make                                # [linux]
  host:
    - python {{ python }}
    - cmake
    - eigen
    - setuptools_scm
    - boost-cpp >= 1.79
    - cxx-compiler
  run:
    - {{ pin_compatible('numpy') }}
    - python
    - netcdf4
    - pyyaml

test:
  imports:
    - pyfes

about:
  home: https://github.com/CNES/aviso-fes
  license: GNU Lesser General Public License v3
  license_family: LGPL
  license_file: COPYING
  summary: 'FES2014 prediction software'
  description: |
    This package is the fully revised version of the FES2014 distribution.
    This distribution includes the FES2014 tidal prediction software and
    the FES2014 tides databases

extra:
  recipe-maintainers:
    - fbriol
