{% set name = "pyfes" %}
{% set version = "2.9.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/CNES/aviso-fes
  git_rev: HEAD

build:
  script: {{ PYTHON }} -m pip install . -vv
  build: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - make                   # [linux or osx]
    - cmake
  host:
    - python {{ python }}
    - libnetcdf
    - setuptools
    - packaging
  run:
    - {{ pin_compatible('numpy') }}
    - python
    - libnetcdf

test:
  imports:
    - pyfes

about:
  home: https://github.com/CNES/aviso-fes
  license: GNU Lesser General Public License v3
  license_family: LGPL
  license_file: COPYING
  summary: 'FES2014 prediction software'
  description: |
    This package is the fully revised version of the FES2014 distribution.
    This distribution includes the FES2014 tidal prediction software and
    the FES2014 tides databases

extra:
  recipe-maintainers:
    - fbriol
