# Copyright (c) 2025 CNES
#
# All rights reserved. Use of this source code is governed by a
# BSD-style license that can be found in the LICENSE file.
"""Generate a Markdown table for the tidal constituents."""

import pathlib

import numpy
import pyfes

ROOT = pathlib.Path(__file__).parent.parent

GREEK_LETTERS = {
    'Alpha': '{\\alpha}',
    'Beta': '{\\beta}',
    'Gamma': '{\\gamma}',
    'Delta': '{\\delta}',
    'Psi': '{\\psi}',
    'Phi': '{\\phi}',
    'Theta': '{\\theta}',
    'Chi': '{\\chi}',
    'Pi': '{\\pi}',
    'Mu': '{\\mu}',
    'Nu': '{\\nu}',
    'Lambda': '{\\lambda}',
    'Eps': '{\\epsilon}',
    'Eta': '{\\eta}',
    'Sigma': '{\\sigma}',
    'Ups': '{\\upsilon}',
    'Rho': '{\\rho}',
    'Tau': '{\\tau}',
}

URL = 'https://cnes.github.io/aviso-fes/core/constituent.html'


def _pretty_name(name: str) -> tuple[str, str | None]:
    """Return the name and its LaTeX representation.

    Convert any Greek letter in name to its LaTeX form. If the name does
    not contain a Greek letter, return the original name and None.
    """
    for greek, latex in GREEK_LETTERS.items():
        if greek in name:
            return name, f'${name.replace(greek, latex)}$'
    return name, None


def url(constituent: pyfes.core.Wave) -> str:
    """Generate a documentation URL for a constituent."""
    return f'{URL}#pyfes.core.{constituent.ident!s}'


def create_constituent_representation() -> str:
    """Generate a Markdown table for the tidal constituents."""
    table = pyfes.WaveTable()
    lines = [
        '| Name | Speed (deg/h) | XDO |',
        '| --- | --- | --- |',
    ]
    data = {}
    for constituent in table:
        component = table[constituent.ident]
        name, greek_notation = _pretty_name(component.name())
        name = f'[{name}]({url(constituent)})'
        if greek_notation:
            name += f' ({greek_notation})'
        frequency = component.freq
        xdo = component.xdo_alphabetical()
        data[constituent.name] = {
            'speed': numpy.degrees(frequency),
            'name': name,
            'xdo': f'{xdo[:1]} {xdo[1:4]} {xdo[4:]}',
        }

    lines.extend(
        f'| {values["name"]} | {values["speed"]:.7f}  | {values["xdo"]} |'
        for values in sorted(data.values(), key=lambda item: item['speed'])
    )
    return '\n'.join(lines)


def main() -> None:
    """Generate the CONSTITUENTS.md file."""
    with open(ROOT / 'CONSTITUENTS.md', 'w') as stream:
        stream.write(f"""# Tidal Constituents

This document provides a comprehensive reference of tidal constituents supported
by the AVISO-FES library. Each constituent represents a harmonic component of
the tidal signal, characterized by its angular speed and Doodson number
representation.

For cross-validation, the table below is compared with the official list of
tidal constituents available at
[this URL](
https://iho.int/mtg_docs/com_wg/IHOTC/IHOTC_Misc/TWCWG_Constituent_list.pdf),
which contains the same information.

**Note:** This file is automatically generated from the wave table. For detailed
technical information about each constituent, including their physical
significance and mathematical formulation, please refer to the [constituent
documentation](https://cnes.github.io/aviso-fes/core/constituent.html).

{create_constituent_representation()}
""")


if __name__ == '__main__':
    main()
