import pathlib

import numpy
import pyfes

ROOT = pathlib.Path(__file__).parent.parent

GREEK_LETTERS = {
    'Alpha': '\\alpha',
    'Beta': '\\beta',
    'Gamma': '\\gamma',
    'Delta': '\\delta',
    'Psi': '\\psi',
    'Phi': '\\phi',
    'Theta': '\\theta',
    'Chi': '\\chi',
    'Pi': '\\pi',
    'Mu': '\\mu',
    'Nu': '\\nu',
    'Lambda': '\\lambda',
    'Eps': '\\epsilon',
    'Eta': '\\eta',
    'Sigma': '\\sigma',
    'Ups': '\\upsilon',
    'Rho': '\\rho',
    'Tau': '\\tau',
}


def _pretty_name(name: str) -> str:
    """
    Convert the greek letter in the name to its LaTeX representation.
    If the name does not contain a greek letter, return it unchanged.
    """
    for greek, latex in GREEK_LETTERS.items():
        if greek in name:
            value = name[-1]
            return f"{name} (${latex} {value}$)"
    return name


def create_constituent_representation() -> str:
    """ """
    table = pyfes.WaveTable()
    lines = [
        '| Name | Speed (deg/h) | XDO |',
        '| --- | --- | --- |',
    ]

    data = {}
    for constituent in table:
        component = table[constituent.ident]
        name = _pretty_name(component.name())
        frequency = component.freq
        xdo = component.xdo_alphabetical()
        data[constituent.name] = {
            'speed': numpy.degrees(frequency),
            'name': name,
            'xdo': f'{xdo[:1]} {xdo[1:4]} {xdo[4:]}',
        }

    lines.extend(
        f"| {values['name']} | {values['speed']:.7f}  | {values['xdo']} |"
        for values in sorted(data.values(), key=lambda item: item['speed']))
    return '\n'.join(lines)


def main():
    """
    Main function to run the script.
    """
    with open(ROOT / 'CONSTITUENTS.md', 'w') as stream:
        stream.write(f"""# Tidal Constituents

This document provides a comprehensive reference of tidal constituents supported
by the AVISO-FES library. Each constituent represents a harmonic component of
the tidal signal, characterized by its angular speed and Doodson number
representation.

**Note:** This file is automatically generated from the wave table. For detailed
technical information about each constituent, including their physical
significance and mathematical formulation, please refer to the [constituent
documentation](https://cnes.github.io/aviso-fes/core/constituent.html).

{create_constituent_representation()}
""")


if __name__ == '__main__':
    main()
