name: CMake

on:
  push:
    branches: [ main, develop]
  pull_request:
    branches: [ main, develop ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu:24.04

    steps:
    - uses: actions/checkout@v2

    - name: Install prerequisite
      run: DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC sudo apt install cmake python3 python3-dev python3-setuptools python3-setuptools-scm python3-pytest python3-yaml python3-numpy python3-netcdf4 git git-lfs g++ libboost-dev libeigen3-dev libopenblas-dev libgtest-dev -q -y

    - name: Initialize the submodules
      run: git submodule update --init --recursive

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DFES_ENABLE_TESTS=ON

    - name: Build Library And Tests
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Running Tests
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}

    - name: Build Python Bindings
      working-directory: ${{github.workspace}}
      run: python3 setup.py build && pytest -vv
