name: CI

on:
  push:
    branches: "*"
  pull_request:
    branches: master

jobs:
  linux:
    name: ${{ matrix.python-version }}-posix
    runs-on:
      - ubuntu-latest
      - windows-2019
      - OSX-latest

    strategy:
      max-parallel: 5
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        mamba-version: "*"
        auto-update-conda: true
        auto-activate-base: false
        activate-environment: test_env
        environment-file: conda/environment.yml

    - name: Build
      shell: bash -l {0}
      run: |
        conda mambabuild --output-folder boa-bld conda/
        anaconda-client upload --force --no-progress --label main --token ${{ secrets.ANACONDA_TOKEN }} --python ${{{ matrix.python-version }}} boa-bld/*/*.tar.bz2
