name: Anaconda Upload

on:
  push:
    branches: "*"
  pull_request:
    branches: master

jobs:
  boa:
    name: ${{ matrix.python-version }}-${{ matrix.os }}
    runs-on:
      - ${{ matrix.os }}

    strategy:
      max-parallel: 5
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
        os: ['ubuntu-latest', 'macos-latest', 'windows-2019']
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        mamba-version: "*"
        auto-update-conda: false
        auto-activate-base: false
        activate-environment: FES
        environment-file: conda/environment.yml

    - name: Build
      shell: bash -l {0}
      run: |
        export ANACONDA_API_TOKEN=${{ secrets.ANACONDA_TOKEN }}
        conda mambabuild --output-folder boa-bld conda/
        anaconda upload --force --no-progress --label main boa-bld/*/*.tar.bz2
